App_Order/urls.py
from django.urls import path
from App_Order import views
 

app_name = 'App_Order'

urlpatterns = [
    path('add/<pk>/', views.add_to_cart, name="add"),
    path('cart/', views.cart_view, name='cart'),
    path('remove/<pk>/', views.remove_from_cart, name="remove"),
    path('increase/<pk>/', views.increase_cart, name="increase"),
    path('decrease/<pk>/', views.decrease_cart, name="decrease"),
    
]

App_Shop/urls.py
from django.urls import path
from App_Shop import views

app_name = 'App_Shop' 

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('product/<pk>/', views.ProductDetail.as_view(), name='product_detail'),
]

My_Ecommarce/urls.py
from django.contrib import admin
from django.urls import path, include
# show Media files
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('App_Login.urls')),
    path('', include('App_Shop.urls')),   
    path('shop/', include('App_Order.urls')),   
    path('payment/', include('App_Payment.urls')),

]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Shop/models.py
from django.db import models
# Category Table
class Category(models.Model):
    title = models.CharField(max_length=20)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Categories"

# Product Table
class Product(models.Model):
    pro_image = models.ImageField(upload_to='Products')
    name = models.CharField(max_length=264)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category')
    preview_text = models.TextField(max_length=200, verbose_name='Preview_Text')
    detail_text = models.TextField(max_length=200, verbose_name='Description')
    price = models.FloatField()
    old_price = models.FloatField(default=0.00)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['-created',]






 

App_Shop/views.py
from django.shortcuts import render
# import view
from  django.views.generic import ListView, DetailView
# models
from App_Shop.models import Product
# Mixin
from django.contrib.auth.mixins import LoginRequiredMixin

class Home(ListView):
    model = Product
    template_name = 'App_shop/home.html'

class ProductDetail(LoginRequiredMixin, DetailView):
    model = Product
    template_name = 'App_Shop/product_detail.html'

 

templates/App_Shop/home.html
{% extends 'base.html' %} 
{% block body_block %}
    <div class="container my-5" >
        <h2 class="">Featured Product</h2>
        <div class="row" style="display: grid; grid-template-columns: repeat(4, 1fr);">
             {% for product in object_list %}
             <div class="">
                <figure class="card card-product">
                    <div class="img-wrap">
                        <img src="/media/{{product.pro_image}}" style="width: 100%; height: 300px;">
                    </div>
                    <figcaption class="info-wrap">
                        <h6 class="title"><a href="{% url 'App_Shop:product_detail' pk=product.pk%}">{{product.name}}</a></h6>
                        <div class="action-wrap">
                            <div class="price-wrap">
                                <span class="price-new">&#2547; {{product.price|floatformat:2}}</span>
                                    <span class="price-old"><strike> &#2547; {{product.old_price|floatformat:2}}</strike></span>
                            </div>
                        </div>
                    </figcaption>
                </figure>
             </div>
             {% endfor %}
        </div>
    </div>
{% endblock %}

    

templates/App_Shop/product_detail.html
{% extends 'base.html' %}
{% block body_block %}
<div class="container my-5">
    <div class="card">
        <div class="row">
            <aside class="col-sm-5 border-right">
                <article class="gallery-wrap">
                    <div class="img-big-wrap">
                        <div>
                             <a href=""><img src="/media/{{object.pro_image}}" style="width: 450px;"></a>
                        </div>
                    </div>
                </article>
            </aside>
            <aside class="col-sm-7">
                <article class="card-body p-5">
                    <h3 class="title mp-3">{{object.name}}</h3>
                    <p class="price-detail-wrap">
                        <span class="price h3 text warning">
                            <span class="currency">BDT &#2547;</span><span>{{object.price}}</span>
                        </span>
                    </p>
                    <dl class="item-property">
                        <dt>Description</dt>
                        <dd>
                            <p>{{object.detail_text}}</p>
                        </dd>
                    </dl>
                    <a href="{% url 'App_Order:add' pk=object.pk %}" class="btn btn-lg btn-outline-primary text-uppercase"><i class="fas fa-shopping-cart"></i>Add to Chart</a>
                </article>
            </aside>
        </div>
    </div>
</div>


 
{% endblock %}
    