App_Order/urls.py
from django.urls import path
from App_Order import views
 

app_name = 'App_Order'

urlpatterns = [
    path('add/<pk>/', views.add_to_cart, name="add"),
    path('cart/', views.cart_view, name='cart'),
    path('remove/<pk>/', views.remove_from_cart, name="remove"),
    path('increase/<pk>/', views.increase_cart, name="increase"),
    path('decrease/<pk>/', views.decrease_cart, name="decrease"),
    
]

App_Payment/urls.py
from django.urls import path
from App_Payment import views

app_name='App_Payment'

urlpatterns = [
    path('checkout/', views.checkout, name="checkout"),
    path('payment/', views.payment, name="payment"),
]

App_Shop/urls.py
from django.urls import path
from App_Shop import views

app_name = 'App_Shop' 

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('product/<pk>/', views.ProductDetail.as_view(), name='product_detail'),
]

My_Ecommarce/urls.py
from django.contrib import admin
from django.urls import path, include
# show Media files
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('App_Login.urls')),
    path('', include('App_Shop.urls')),   
    path('shop/', include('App_Order.urls')),   
    path('payment/', include('App_Payment.urls')),

]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Order/models.py
from django.db import models
from django.conf import settings
#Model
from App_Shop.models import Product

class Cart(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="cart" )
    item = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    purchased = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    Updated = models.DateTimeField(auto_now=True)

     

    
    def __str__(self):
         return f'{self.quantity} X {self.item}'

    def get_total(self):
         total = self.item.price * self.quantity
         float_total = format(total, '0.2f')
         return float_total
    
class Order(models.Model):
     orderitems = models.ManyToManyField(Cart)
     user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
     ordered = models.BooleanField(default=False)
     created = models.DateTimeField(auto_now_add=True)
     paymentId = models.CharField(max_length=264, blank=True, null=True)
     orderId = models.CharField(max_length=200, blank=True, null=True)


     def get_totals(self):
          total = 0
          for order_item in self.orderitems.all():
               total = total + float(order_item.get_total())
          return total
               


     
     
    
    

App_Order/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
# Authentication
from django.contrib.auth.decorators import login_required
from App_Order.models import Cart, Order
from App_Shop.models import Product
#  Messages
from django.contrib import messages

# Create your views here.

@login_required
def add_to_cart(request, pk):
    item = get_object_or_404(Product, pk=pk)
    order_item = Cart.objects.get_or_create(item=item, user=request.user, purchased=False)
    order_qs = Order.objects.filter(user=request.user, ordered= False)

    if order_qs.exists():
        order = order_qs[0]
        if order.orderitems.filter(item=item).exists():
            order_item[0].quantity += 1
            order_item[0].save()
            messages.info(request, "This item was added to your cart.")
            return redirect("App_Shop:home")
        else:
            order.orderitems.add(order_item[0])
            messages.info(request, "This item was added to your cart.")
            return redirect("App_Shop:home")


    else:
        order = Order(user=request.user)
        order.save()
        order.orderitems.add(order_item[0])
        messages.info(request, "This item was added to your Cart.")
        return redirect("App_shop:home")
    
@login_required
def cart_view(request):
    carts = Cart.objects.filter(user=request.user, purchased=False)
    orders = Order.objects.filter(user=request.user, ordered=False)
    
    if carts.exists() and orders.exists():
        order = orders[0]
        return render(request, 'App_Order/cart.html', context={'carts': carts, 'order': order})
    else:
        messages.warning(request, "You don't have any items in your cart!")
        return redirect(reverse('App_Shop'))  # Use reverse to get the URL pattern name
    


@login_required
def remove_from_cart(request, pk):
    item = get_object_or_404(Product, pk=pk)
    order_qs = Order.objects.filter(user=request.user, ordered= False)

    if order_qs.exists():
        order = order_qs[0]
        if order.orderitems.filter(item=item).exists():
            order_item = Cart.objects.filter(item=item, user= request.user, purchased=False)[0]
            order.orderitems.remove(order_item)
            order_item.delete()
            messages.warning(request, "This item was removed from  your cart.")
            return redirect("App_Order:cart")
        else:
             
            messages.info(request, "This item was not on your cart.")
            return redirect("App_Shop:home")
        
    else:
        messages.info(request, "You don't have an active order")
        return redirect('App_Shop:home')
    

@login_required
def increase_cart(request, pk):
    item = get_object_or_404(Product, pk=pk)
    order_qs = Order.objects.filter(user=request.user, ordered= False)

    if order_qs.exists():
        order = order_qs[0]
        if order.orderitems.filter(item=item).exists():
            order_item = Cart.objects.filter(item=item, user= request.user, purchased=False)[0]
            if order_item.quantity >= 1:
                order_item.quantity += 1
                order_item.save()
                messages.warning(request, f"{item.name} quantity has been updated.")
                return redirect('App_Order:cart')

        else:
            messages.warning(request, f"{item.name} is not in  your cart.")
                 
    else:
        messages.info(request, "You don't have an active order")
        return redirect(reverse('App_Shop'))
@login_required
def decrease_cart(request, pk):
    item = get_object_or_404(Product, pk=pk)
    order_qs = Order.objects.filter(user=request.user, ordered= False)

    if order_qs.exists():
        order = order_qs[0]
        if order.orderitems.filter(item=item).exists():
            order_item = Cart.objects.filter(item=item, user= request.user, purchased=False)[0]
            if order_item.quantity > 1:
                order_item.quantity -= 1
                order_item.save()
                messages.warning(request, f"{item.name} quantity has been updated.")
                return redirect('App_Order:cart')

            else:
                order.orderitems.remove(order_item)
                order_item.delete()
                messages.warning(request, f"{item.name} item has been removed.")
                return redirect('App_Shop:home')

        else:
            messages.warning(request, f"{item.name} is not in  your cart.")
                 
    else:
        messages.info(request, "You don't have an active order")
        return redirect('App_Shop:home')

        
    

templates/App_Order/cart.html
{% extends 'base.html' %}

{% block body_block %}

<div class="container my-5">
    <div class="my-5">
        <h2>Your Cart</h2>
    </div>
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col" width="15%">#</th>
                <th scope="col">Product Name</th>
                <th scope="col">Quantity</th>
                <th scope="col" align="right">Price</th>
                <th scope="col">Remove</th>
            </tr>
        </thead>
        <tbody>
            
            {% for cart in carts %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ cart.item.name }}</td>
                    <td>
                        <a href="{% url 'App_Order:decrease' pk=cart.item.pk %}" class="mr-2"><span class="badge badge-light"><i class="fas fa-minus"></i></span></a>
                        {{ cart.quantity }}
                        <a href="{% url 'App_Order:increase' pk=cart.item.pk %}" class="mr-2"><span class="badge badge-light"><i class="fas fa-plus"></i></span></a>
                    
                    </td>
                    <td align="right">&#2547;{{ cart.get_total }}</td>
                    <td><a href="{% url 'App_Order:remove' pk=cart.item.pk  %}" class="btn btn-danger btn-sm">Remove From Cart</a></td>
                </tr>
                
            {% endfor %}
            <tr>
                <th scope="row"></th>
                <td colspan="2">Total</td>
                <td align="right">&#2547; {{ order.get_totals | floatformat:2 }}</td>
            </tr>
            <tr>
                <th scope="row"></th>
                <td colspan="4" class="text-right">
                    <a href="{% url 'App_Shop:home' %}" class="btn btn-warning mr-4">Continue Shoping</a>
                    <a href="{% url 'App_Payment:checkout' %}" class="btn btn-success mr-4">Proceed To Checkout</a>
                </td>

            </tr>
                
        </tbody>
    </table>
</div>
    
{% endblock body_block %}