App_Login/urls.py
from django.urls import path
from App_Login import views
app_name = 'App_Login'
urlpatterns = [
    path('signup/', views.sign_up, name='signup'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.user_profile, name='profile'),
]

App_Order/urls.py
from django.urls import path
from App_Order import views
 

app_name = 'App_Order'

urlpatterns = [
    path('add/<pk>/', views.add_to_cart, name="add"),
    path('cart/', views.cart_view, name='cart'),
    path('remove/<pk>/', views.remove_from_cart, name="remove"),
    path('increase/<pk>/', views.increase_cart, name="increase"),
    path('decrease/<pk>/', views.decrease_cart, name="decrease"),
    
]

App_Shop/urls.py
from django.urls import path
from App_Shop import views

app_name = 'App_Shop' 

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('product/<pk>/', views.ProductDetail.as_view(), name='product_detail'),
]

My_Ecommarce/urls.py
from django.contrib import admin
from django.urls import path, include
# show Media files
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('App_Login.urls')),
    path('', include('App_Shop.urls')),   
    path('shop/', include('App_Order.urls')),   
    path('payment/', include('App_Payment.urls')),

]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
      <!-- Include Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>{% block title_block %} My Ecommerce {% endblock %}</title>
</head>
<body>
    {% include 'navbar.html' %}
    <div class="container">
        <div class="msg container mt-2">
            {% if messages %}
                {% for message in messages %}
                    <div {% if message.tags %} class="alert alert-{{message.tags}}{% endif %}" role="alert">
                         {{message}} 
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div> 
                {% endfor %}
            {% endif %}
        </div>
        {% block body_block %}{% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-eZpElG7F/Ji1ByhOHxBYvHyV7P0FIVjr7fHpiMquS+qnUJ4Gk57lgKgWdLyZmO4" crossorigin="anonymous"></script>
    
</body>
</html>

templates/navbar.html
 {% load cart_tag %}
 <nav class="navbar navbar-expand-lg navbar-light bg-light mx-auto container-lg">
        <a class="navbar-brand" href="{% url 'App_Shop:home' %}">My Ecommerce Site</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                {% if request.user.is_authenticated %}
                <li class="nav-item"><a href="{% url 'App_Order:cart' %}" class="nav-link"><i class="fa fa-shopping-cart"></i> Cart
                <span class="badge badge-light">{{ request.user | cart_total }}</span></a>
                    
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-user-tie"></i> {{ request.user.profile.username }}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'App_Login:profile' %}">Profile</a>
                        <a class="dropdown-item" href="#">Orders</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'App_Login:logout' %}">Logout</a>
                    </div>
                </li>
                {% else %}
                <li>
                    <a href="{% url 'App_Login:login' %}" class="btn btn-primary">Login</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    