App_Payment/urls.py
from django.urls import path
from App_Payment import views

app_name='App_Payment'

urlpatterns = [
    path('checkout/', views.checkout, name="checkout"),
    path('payment/', views.payment, name="payment"),
]

App_Shop/urls.py
from django.urls import path
from App_Shop import views

app_name = 'App_Shop' 

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('product/<pk>/', views.ProductDetail.as_view(), name='product_detail'),
]

My_Ecommarce/urls.py
from django.contrib import admin
from django.urls import path, include
# show Media files
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('App_Login.urls')),
    path('', include('App_Shop.urls')),   
    path('shop/', include('App_Order.urls')),   
    path('payment/', include('App_Payment.urls')),

]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Payment/models.py
from django.db import models
from django.conf import settings

# Create your models here.

class BillingAddress(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    address = models.CharField(max_length=264, blank=True)
    zipcode = models.CharField(max_length=10, blank=True)
    city = models.CharField(max_length=30, blank=True)
    country = models.CharField(max_length=20, blank=True)

    def __str__(self):
        return f"{self.user.username} billing address"

    def is_fully_filled(self):
        field_names = [f.name for f in self._meta.get_fields()]

        for field_name in field_names:
            value = getattr(self, field_name)
            if value is None or value == '':
                return False

        return True

    class Meta:
        verbose_name_plural = "Billing Addresses"

App_Payment/forms.py
from django import forms
from .models import BillingAddress  # Import the BillingAddress model from your models.py

class BillingForm(forms.ModelForm):
    class Meta:
        model = BillingAddress  # Associate the form with the BillingAddress model
        fields = ['address', 'zipcode', 'city', 'country']  # Specify the fields you want in the form

App_Payment/views.py
from django.shortcuts import render
from App_Order.models import Order
from App_Payment.forms import BillingAddress
from App_Payment.forms import BillingForm
from django.contrib import messages
from django.shortcuts import redirect


from django.contrib.auth.decorators import login_required
# for payment
# import requests
# from sslcommerz_python.payment import SSLCSession
# from decimal import Decimal 
# import socket


@login_required
def checkout(request):
    saved_address = BillingAddress.objects.get_or_create(user=request.user)
    saved_address = saved_address[0]
    form = BillingForm(instance=saved_address)
    if request.method =="POST":
        form = BillingForm(request.POST, instance=saved_address)
        if form.is_valid():
            form.save()
            form = BillingForm(instance=saved_address)
            messages.success(request, f"successfully Address saved")
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    order_items = order_qs[0].orderitems.all()
    order_total = order_qs[0].get_totals()
    

    return render(request, 'App_Payment/checkout.html', context={'form':form, 'order_items':order_items, 'order_total':order_total, 'saved_address':saved_address})

@login_required
def payment(request):
    saved_address, created = BillingAddress.objects.get_or_create(user=request.user)
    
    if not saved_address.is_fully_filled():
        messages.info(request, "Please complete the shipping address!")
        return redirect("App_Payment:checkout")
    
    if not request.user.Profile.is_fully_filled():
        messages.info(request, "Please complete Profile Details!")
        return redirect("App_Login:change_profile")
    
    return render(request, "App_Payment/payment.html", context={})

templates/App_Payment/checkout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body_block %}
    <div class="container my-5">
        <h2 class="mb-3">Shipping Address > <span class="text-muted">Checkout</span></h2>
        <div class="row">
            <div class="col-md-9">
                <div class="card mb-5" style="height: auto;">
                    <div class="card-body">
                        <form method="POST">
                            {{ form|crispy }}
                            {% csrf_token %}
                            <button type="submit" class="btn btn-primary float-right">Save Address</button>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card" style="height: auto;">
                    <div class="card-body">
                        <ul class="list-group list-group-flush">
                            
                            {% for order_item in order_items %}
                                <li class="list-group-item">
                                    {{ order_item.item.name }} x {{ order_item.quantity }}
                                </li>
                                
                            {% endfor %}
                                
                        </ul>
                    </div>
                    <div class="card-footer">
                        <span class="float-left"><b>Order Total</b></span>
                        <span class="float-right"><b>{{ order_total|floatformat:2 }}</b></span>
                    </div>
                </div>

                <br>
                <br>
                {% if saved_address.is_fully_filled %}
                    <a href="{% url "App_Payment:payment" %}" class="btn btn-warning btn-md">Make Payment</a>
                {% else %}
                    <div class="alert alert-info">
                        <p>Please fill up all the information to make payment</p>
                    </div>
                {% endif %}
                    
            </div>
        
        </div>

    </div>
    
{% endblock %}